### ISSUE TITLE
Only weapon can be putted on the slotfast?

### ISSUE THREAD

**Issue by BryBTG** [MaoriRP/Maori_Inventory#2]
Only weapon can be putted on the slotfast? Nice script btw.

**Comment by mrdigital0** [comment]
Yes at the moment only Weapons can be put in the hot key area... i am figuring out how to do it for items

**Comment by hemato** [comment]
> Yes at the moment only Weapons can be put in the hot key area... i am figuring out how to do it for items

when you put weapon to fastslot the weight of weapon is ignored. :/
