### ISSUE TITLE
Resoluçao de Ecra

### ISSUE THREAD

**Issue by Ranger194** [MaoriRP/Maori_Inventory#25]
Bom dia, tenho uma duvida introduzi o inventario funciona 5* mas existe um problema, alguns jogadores com resoluçoes abaixo de 1920x1080  nao conseguem bem utilizar o ecra, existe maneira de reajustar automaticamente?

Obrigado

**Comment by iSentrie** [comment]
yes, edit .css and .html if needed

**Comment by JMCLC** [comment]
@Ranger194 Isso será corrigido no update do novo design que farei assim que possível
