### ISSUE TITLE
Missing license and credits of original resource

### ISSUE THREAD

**Issue by Trsak** [MaoriRP/Maori_Inventory#28]
Hello,
your code comes from original esx_inventoryhud that was released under GNU GPL v3 license.

You have to use the same license and keep credits of the original resource:
`Original esx_inventoryhud resource made by Trsak.`

Please take your time to do this or i will be forced to make DMCA report and your code will be taken down. 
Thanks.

**Comment by JMCLC** [comment]
@Trsak yeah sry dude forgot to add the credits altough the license was already the same as yours
